const env = {
	TURSO_DATABASE_URL: process.env.TURSO_DATABASE_URL,
	TURSO_AUTH_TOKEN: process.env.TURSO_AUTH_TOKEN,
	GLOBAL_HOST: process.env.GLOBAL_HOST,

	// below are sent to client
	SPACE_NAME: process.env.SPACE_NAME,
	OWNER_ID: process.env.OWNER_ID,
	DOWNVOTE_ADDRESS: process.env.DOWNVOTE_ADDRESS,
	TOKEN_ID: process.env.TOKEN_ID || '',
	CONTENT_LIMIT: Number(process.env.CONTENT_LIMIT) || undefined,
	TAG_LIMIT: Number(process.env.TAG_LIMIT) || undefined,
	ANYONE_CAN_JOIN: process.env.ANYONE_CAN_JOIN === 'true' || undefined,
	ANYONE_CAN_ADD: process.env.ANYONE_CAN_ADD === 'true' || undefined,
	DELETABLE_VOTES: process.env.DELETABLE_VOTES === 'true' || undefined,
	TAG_TREE: {
		parents: {
			AI: ['Artificial Intelligence'],
			'AI SaaS': ['Perplexity'],
			Activism: ['Protest'],
			Actor: ['Keanu Reeves'],
			Advertisement: ['Engaging Advertisement'],
			Africa: ['African', 'Ghana', 'South Africa'],
			African: ['Africa'],
			Aircraft: ['Drone'],
			Algorithm: ['Data Structure', 'Regular Expression'],
			'Alphabet Inc.': ['YouTube'],
			Amazon: ['Amazon Review'],
			Analysis: ['Review'],
			Anatomy: ['Human Anatomy', 'Skin'],
			Animal: ['Baboon', 'Bug', 'Chicken'],
			Aphorism: ['Latin Aphorism'],
			'Apple Inc.': ['iOS', 'mac', 'Mac Mini', 'macOS', 'Shot on iPhone'],
			Architecture: [
				'Construction Material',
				'Hostile Architecture',
				'Housing',
				'Insulation',
				'Plumbing',
			],
			Art: [
				'Aesthetic',
				'Architecture',
				'Cryptography',
				'Dance',
				'Impermanent Art',
				'Interior Design',
				'Sculpting',
				'Sculpture',
				'Unintentional Art',
			],
			'Artificial Intelligence': ['AI', 'AI Limitation', 'AI Music', 'AI SaaS', 'AI Video'],
			Asia: ['Asian', 'East Asia'],
			Athlete: ['Fighter', 'Japanese Athlete'],
			'Audio Gear': ['Earbud', 'Microphone'],
			Aviation: ['Aircraft', 'Airline'],
			Baseball: ['Basketball Player'],
			'Bay Area': ['Oakland', 'r/bayarea', 'r/Gunn', 'San Francisco', 'San Jose', 'Silicon Valley'],
			Beekeeping: ['Bee Behavior', 'Beehive'],
			Bicycle: ['Bicycle Framebuilding'],
			Book: ['Ebook', 'Textbook'],
			Brazil: ['Bossa Nova'],
			Bureaucracy: ['Leadership'],
			Business: ['Business Acquisition', 'Business Pivot', 'Enshittification'],
			CLI: ['Command-Line Interface'],
			CSS: ['Cascading Style Sheets'],
			California: ['Bay Area', 'Los Angeles', 'San Diego'],
			Camping: ['Sleeping Bag'],
			Canada: ['Asian Canadian'],
			Car: ['Pickup Truck'],
			'Car Industry': ['Car', 'Car Restoration'],
			'Cascading Style Sheets': ['CSS'],
			Chicken: ['Poultry Farming'],
			China: [
				'Chinese American Cultural Export',
				'Chinese Cultural Export',
				'Chinese Food',
				'Chinese Language',
				'Hong Kong',
			],
			'Chinese Cultural Export': [
				'Chinese Food',
				'Chinese Language',
				'Chinese Music',
				'Chinese Proverb',
			],
			'Chinese Language': ['Cantonese Language', 'Learn Chinese', 'Mandarin Language'],
			'Chinese Music': ['純音樂 - Topic'],
			Cinematography: [
				'Animation',
				'Documentary',
				'Movie',
				'Shot on iPhone',
				'Stop Motion',
				'TV Show',
			],
			City: ['San Diego', 'San Francisco'],
			Clothing: ['Shoe'],
			'Cloud Platform': ['Fly.io'],
			Coding: ['Debugging'],
			College: ['College Admissions', 'Ivy League', 'MIT', 'Princeton'],
			Comedian: ['Key & Peele', 'Sam Hyde'],
			'Comedic Music Artist': ['Jonathan Coulton'],
			Comedy: [
				'Blooper',
				'British Humor',
				'Comedian',
				'Comedic Remark',
				'Comedy Movie',
				'Funny',
				'Impression',
				'Joke',
				'Parody',
				'Satire',
				'Skit',
				'Stand-Up Comedy',
				'Unintentional Humor',
			],
			'Command-Line Interface': ['CLI'],
			Commerce: ['E-Commerce'],
			Communication: [
				'Brutally Honest Remark',
				'Clarification',
				'Interview',
				'Linguistics',
				'Mail',
				'Monologue',
				'News Broadcasting',
				'Presentation',
			],
			Company: [
				'Alphabet Inc.',
				'Amazon',
				'Anduril Industries',
				'Apple Inc.',
				'Microsoft',
				'Reddit',
				'Startup',
				'Twitter',
			],
			Computer: ['Command-Line Interface', 'File System', 'Software'],
			'Computer Hardware': ['Raspberry Pi'],
			'Computer Networking': ['Internet'],
			'Computer Science': ['Computer Vision', 'Data Structure', 'Large Language Model'],
			Condition: ['COVID-19', 'Degeneracy', 'Disability', 'Obesity'],
			'Consumer Awareness': ['Grift'],
			Consumerism: ['Consumer Awareness', 'For Sale'],
			Continent: ['Africa', 'Asia', 'Europe'],
			Cooking: ['Ingredient', 'Learn to Cook'],
			Country: [
				'Brazil',
				'Britain',
				'Dubai',
				'Germany',
				'Ghana',
				'India',
				'Israel',
				'Italy',
				'Jamaica',
				'Japan',
				'Mexico',
				'Micronation',
				'Network State',
				'North Korea',
				'Portugal',
				'Saudi Arabia',
				'South Africa',
				'South Korea',
				'Switzerland',
				'Taiwan',
				'Thailand',
				'United States of America',
				'Vietnam',
			],
			Cryptocurrency: ['Blockchian Protocol', 'Tokenomics'],
			Cryptography: ['Cryptocurrency'],
			Culture: ['Asian', 'Cultural Appropriation', 'Internet', 'Meme'],
			Cycling: ['Bicycle', 'Bike Route', 'Bike Trail'],
			DIY: ['Do It Yourself'],
			'Data Storage': ['PocketBase', 'SQLite'],
			Dessert: ['Candy', 'Ice Cream', 'Pastry'],
			Destruction: [
				'Crash',
				'Explosion',
				'Fire',
				'Manmade Disaster',
				'Mass Casualty Incident',
				'Natural Disaster',
			],
			'Do It Yourself': ['DIY', 'Repair'],
			Drama: ['Hoax', 'Lawsuit'],
			'E-Commerce': ['Online Store'],
			'East Asia': ['China', 'Japan', 'North Korea', 'South Korea', 'Taiwan', 'Vietnam'],
			Eatery: ['Bakery', 'Restaurant'],
			Education: ['Language Learning', 'Mnemonic', 'Teaching English'],
			Efficiency: ['Low-cost'],
			'Electrical Engineering': ['Battery', 'Electric Transportation', 'MOSFET'],
			Engineering: ['Electrical Engineering', 'Robot'],
			Entrepreneurship: ['Entrepreneur', 'Indie Hacking', 'Side Hustle', 'Startup', 'Y Combinator'],
			Environmentalism: ['Pest Control', 'Repurpose'],
			Era: ['1960s', '1970s', '1980s', '1990s', '2000s'],
			Ethics: ['Parable'],
			Europe: ['European History', 'France', 'Germany', 'Italy', 'Spain'],
			Event: [
				'Competition',
				'Meetup',
				'Music Festival',
				'Online Event',
				'Recurring Event',
				'Unsanctioned Event',
			],
			'Exceptional Person': [
				'Balaji Srinivasan',
				'Donald Trump',
				'George Hotz',
				'Hayao Miyazaki',
				'Masanobu Fukuoka',
				'Terence McKenna',
			],
			Exercise: ['Calisthenics', 'Dance'],
			Farming: ['Cattle', 'Farming Practice', 'Land', 'Poultry Farming', 'Soil'],
			'Farming Practice': ['Aquaculture', 'Industrial Agriculture', 'Permaculture'],
			Fashion: ['Clothing'],
			Fighter: ['Bob Sapp', 'Boxer'],
			Finance: ['Inflation', 'Tax'],
			Fishing: ['Seafood'],
			Food: ['Chicken', 'Cooking', 'Dessert', 'Seafood'],
			'Foreign Music': [
				'Chinese Music',
				'Greek Term',
				'Indian Music',
				'Japanese Music',
				'Korean Music',
				'Thai Music',
			],
			'Foreign Term': ['Arabic Term', 'French Term', 'Japanese Term', 'Korean Term'],
			France: ['French Language'],
			'French Language': ['French Term'],
			Fungus: ['Mushroom'],
			Gadget: ['Audio Gear'],
			Gambling: ['Poker', 'Sports Betting'],
			'Gen Z': ['Gen Z Humor'],
			Generation: ['Baby Boomer Generation', 'Gen Alpha', 'Gen Z'],
			Geography: ['Continent', 'Country', 'Nordic Country'],
			Governance: ['Government Job', 'Politics'],
			'Graphic Art': ['Animation', 'Blender', 'User Interface', 'Visual Artist'],
			'Group of People': ['Community', 'Cult', 'Society'],
			Health: [
				'Alternative Medicine',
				'Anatomy',
				'Body Skill',
				'Exercise',
				'First Aid',
				'Hair Care',
				'Mental Health',
				'Nutrition',
				'Physical Rehabilitation',
				'Safety',
				'Sleep',
				'Yoga',
			],
			History: ['Era'],
			Hobby: [
				'3D Printing',
				'Art',
				'Beekeeping',
				'Bicycle',
				'Boating',
				'Camping',
				'Fishing',
				'Gardening',
				'Guitar',
				'Photography',
				'Sculpting',
				'Soap Making',
				'Sport',
				'Volunteering',
				'Woodworking',
				'Yoga',
			],
			Housing: [
				'Couch Surfing',
				'Free Room and Board',
				'Homestay',
				'Section 8',
				'Shipping Container Housing',
				'Studio Tour',
			],
			Ideology: ['Fascism'],
			Illinois: ['Chicago'],
			'Industrial Society': ['Food Delivery', 'Industrial Agriculture', 'Manufacturing'],
			Ingredient: ['Coconut Oil'],
			Instrument: ['Guitar', 'Piano', 'Saxophone'],
			'Interior Design': ['Furniture'],
			Internet: ['Cybersecurity', 'Network State'],
			'Internet Browser': ['Chrome Extension'],
			'Internet Protocol': ['Blockchian Protocol'],
			Interview: ['Street Interview'],
			Italy: ['Rome'],
			Japan: [
				'Anime',
				'Japan Countryside',
				'Japanese American',
				'Japanese Cultural Export',
				'Japanese Language',
				'Japanese Music',
				'Japanese Village',
				'Kyoto',
			],
			'Japanese Cultural Export': [
				'Engrish',
				'Japanese Food',
				'Japanese Humor',
				'Japanese Language',
				'Japanese Movie',
				'Japanese Music',
			],
			'Japanese Language': ['Japanese Saying', 'Japanese Term'],
			'Japanese Music': ['Anime Music', 'Denpa Music', 'Serani Poji - Topic', '聞人聽書_ - Topic'],
			'Japanese Music Artist': ['Joe Hisaishi Official'],
			'Japanese Term': ['Japanese Slang', 'Japanese Vocabulary List'],
			Journalism: ['Journalist'],
			Korea: ['Korean Music', 'Korean Term', 'North Korea', 'South Korea'],
			'Korean Music': ['IU', '장윤주 - Topic'],
			'Korean Term': ['Mukbang'],
			LLM: ['Large Language Model'],
			Labor: [
				'Apprenticeship',
				'Burnout',
				'Business',
				'Cybersecurity',
				'Government Job',
				'Hiring',
				'Job Automation',
				'Job Opening',
				'Job Seeking',
				'Minimum Wage',
				'Productivity',
				'Quiet Quitting',
				'Quitting',
				'Retirement',
				'Side Hustle',
				'Slavery',
				'Work Culture',
			],
			Landform: ['River'],
			'Language Learning': ['Teaching English'],
			Laptop: ['Thinkpad'],
			'Large Language Model': ['LLM'],
			'Latin America': ['Mexico', 'Venezuela'],
			'Learn Japanese': [
				'English with Japanese Subtitles',
				'Japanese with English Subtitles',
				'Japanese with Japanese Subtitles',
				'Practice Japanese',
			],
			'Legal System': ['Lawsuit', 'Sentencing'],
			Lifestyle: [
				'Expatriate',
				'Gap Year',
				'Life Advice',
				'Life Hack',
				'Retirement',
				'Travel',
				'Van Life',
			],
			Linguistics: [
				'Acronym',
				'Adjective',
				'Alliteration',
				'Arabic Term',
				'Engrish',
				'Euphemism',
				'Idiom',
				'Initialism',
				'Japanese Language',
				'Korean Term',
				'Language Learning',
				'Literary Technique',
				'Portmanteau',
				'Pronunciation',
				'Rhyme',
				'Saying',
				'Semantics',
				'Teaching English',
				'Term',
				'Word',
			],
			Logic: ['Algorithm'],
			Logistics: ['Supply Chain'],
			'Low-cost': ['Do It Yourself'],
			Manufacturing: ['Metalworking', 'Woodworking'],
			Marketplace: ['Online Marketplace'],
			Marriage: ['Divorce'],
			Maryland: ['Baltimore'],
			Math: ['Mathematics'],
			Mathematics: ['Cryptography', 'Game Theory', 'Geometry', 'Math', 'Statistics'],
			Meme: ['Donald Trump', 'Shrek', 'SpongeBob'],
			Meteorology: ['Weather'],
			Mexico: ['Mexican Cultural Export'],
			Money: ['ATM', 'Finance'],
			Movie: [
				'Action Comedy Movie',
				'Comedy Movie',
				'Drama Movie',
				'Romance Movie',
				'Science Fiction Movie',
				'Sports Movie',
				'War Movie',
			],
			Music: [
				'573 - Topic',
				'Cindy - Topic',
				'Colin Willsher - Topic',
				'Collin Lim - Topic',
				'Cover Music',
				'Daniel Perret - Topic',
				'Delacour - Topic',
				'Dorothy Collins - Topic',
				'Earworm',
				'Foreign Music',
				'Hip Hop',
				'Home Made Kazoku - Topic',
				'Instrumental',
				'Mashup',
				'Music Album',
				'Music Theory',
				'Opera',
				'potsu',
				'Release - Topic',
				'SEGA SOUND TEAM - Topic',
				'Serani Poji - Topic',
				'Solomon Fox - Topic',
				'Tshxlx Irl - Topic',
				'US Army Field Band - Topic',
			],
			'Music Artist': [
				'Comedic Music Artist',
				'David Bowie',
				'DJ',
				'Jack Stauber',
				'Jack Stauber Music',
				'Japanese Music Artist',
				'Ludwig Goransson',
			],
			'Music Genre': [
				'AI Music',
				'Boinging Music',
				'Bossa Nova',
				'Calming Music',
				'Catchy Music',
				'Cheerful Music',
				'Chill Music',
				'Chinese Music',
				'Country Music',
				'Cover Music',
				'Denpa Music',
				'Elevator Music',
				'Epic Music',
				'Foreign Music',
				'Funny Music',
				'Groovy Music',
				'Indian Music',
				'Japanese Music',
				'Korean Music',
				'Live Rendition',
				'Meme Music',
				'Remix',
				'Rock Music',
				'Slow + Reverb Music',
				'Soft Rock Music',
				'Soothing Music',
				'Soul Music',
				'Techno',
				'Thai Music',
				'Trance Music',
				'Vaporwave',
				'Video Game Music',
			],
			'Music Group': ['OfficialEels', 'yesofficial'],
			'Music Industry': [
				'Audio Gear',
				'Music',
				'Music Festival',
				'Music Genre',
				'Music Group',
				'Music Production',
			],
			'Music Production': ['Audio Gear', 'Sound Bite'],
			NPC: ['Non-Player Character'],
			NYC: ['New York City'],
			'Natural Disaster': ['Earthquake'],
			Nature: [
				'Agriculture',
				'Animal',
				'Aquaculture',
				'Beekeeping',
				'Environmentalism',
				'Farming',
				'Fungus',
				'Gardening',
				'Landform',
				'Plant',
				'Sex',
				'Soil',
			],
			'New York': ['New York City'],
			'New York City': ['NYC'],
			'Non-Player Character': ['NPC'],
			'Nordic Country': ['Iceland', 'Norway'],
			Norway: ['Norwegian Cultural Export', 'r/Norway'],
			Nutrition: [
				'Drink',
				'Eatery',
				'Food',
				'Food Delivery',
				'Food Poisoning',
				'Food Storage',
				'Mukbang',
				'Plant-Based Diet',
			],
			OPSEC: ['Operations Security'],
			OSINT: ['Open Source Intelligence'],
			'Online Marketplace': ['Craigslist'],
			'Open Source': ['Open Source Intelligence', 'Open Source Software'],
			'Open Source Intelligence': ['OSINT'],
			'Open Source Software': ['Blender'],
			Opera: ['Opera Singer'],
			'Operating System': ['Android', 'Linux'],
			'Operations Security': ['OPSEC'],
			Opinion: ['Criticism'],
			Parenting: ['Adoption'],
			'Party Trick': ['Body Skill'],
			People: ['Chinese Philosopher', 'Past Coworker', "Person I've Met", 'Politician'],
			"Person I've Met": ['Anastasia Shaura', 'Former Classmate'],
			'Person Type': [
				'Actor',
				'African American',
				'Creator',
				'Foreigner',
				'Japanese American',
				'Music Artist',
				'Nerd',
				'Non-Player Character',
				'Scammer',
				'Whistleblower',
				'White Liberal',
			],
			Phenomenon: [
				'Conspiracy',
				'Conspiracy Theory',
				'Earworm',
				'Glitch',
				'Gray Area',
				'Misconception',
				'Nostalgia',
				'Paradox',
				'Prescient',
				'Uncanny Valley',
			],
			Philosopher: ['Chinese Philosopher'],
			Philosophy: ['Buddhism', 'Epistemology', 'Marxism', 'Philosopher', 'Taoism'],
			Photography: ['Photograph', 'Shot on iPhone'],
			Physics: ['Rocket Science'],
			Place: ['Coworking Space', 'Eatery', 'Hackerspace', 'Museum', 'Point of Interest'],
			Plant: ['Cannabis', 'Hygienic Plant', 'Tomato'],
			Podcast: ['Lex Fridman Podcast', 'The Joe Rogan Experience'],
			Policy: ['Death Penalty', 'Illegal Immigration', 'Martial Law', 'Sentencing', 'Tax'],
			'Political Ideology': [
				'Capitalism',
				'Communism',
				'Corporatism',
				'Marxism',
				'Nimbyism',
				'Wokism',
			],
			Politician: ['Adolf Hitler', 'Donald Trump', 'Joe Biden'],
			Politics: ['Policy', 'Political Gaffe', 'Political Ideology', 'Politician'],
			Portugal: ['Lisbon'],
			Prediction: ['Prescient'],
			Protest: ['Quitting'],
			Proverb: ['Chinese Proverb'],
			Psychology: ['Uncanny Valley'],
			Quitting: ['Quiet Quitting'],
			Quote: ['Opinion', 'Personal Anecdote'],
			Reading: ['Biography'],
			'Real Estate': ['Real Estate Listing'],
			'Recurring Event': ['Annual Event', 'Semi-Annual Event'],
			Reddit: ['Reddit Comment', 'Subreddit'],
			Relationships: ['Dating', 'Marriage'],
			Religion: ['Buddhism', 'Christianity', 'Islam', 'Judaism', 'Mormonism'],
			Review: ['Amazon Review', 'Book Review', 'Comparison'],
			Rome: ['Roman Empire'],
			SF: ['San Francisco'],
			SQLite: ['Turso'],
			Safety: ['Insurance', 'Operations Security', 'Privacy'],
			Sales: ['Advertisement'],
			'San Francisco': ['SF'],
			Saying: ['Aphorism', 'Proverb', 'Quote'],
			Scam: ['Fraud', 'Ponzi Scheme', 'Scammer'],
			Scammer: ['Scam'],
			Science: [
				'Anatomy',
				'Chemistry',
				'Geology',
				'Neuroscience',
				'Physics',
				'Psychology',
				'Rocket Science',
			],
			Sentencing: ['Death Penalty'],
			'Social Media': ['Facebook', 'Instagram', 'Snapchat', 'TikTok', 'Twitter', 'Vine', 'YouTube'],
			Society: ['Doomsday', 'Dystopia', 'Futurism', 'Industrial Society'],
			Sociology: [
				'Activism',
				'Culture',
				'Ethics',
				'Feminism',
				'Homeless',
				'Immigration',
				'Racism',
				'Relationships',
				'Social Norm',
				'Socializing',
				'Society',
				'Welfare',
			],
			Software: ['Open Source Software'],
			'South Korea': ['South Korean Cultural Export'],
			Spirituality: ['Buddhism'],
			SpongeBob: ['SpongeBob Cultural Export'],
			Sport: ['American Football', 'Baseball', 'Breakdance', 'Cycling', 'Running'],
			Statistics: ['Statistic'],
			Subreddit: [
				'r/askphilosophy',
				'r/bayarea',
				'r/careeradvice',
				'r/Documentaries',
				'r/georgism',
				'r/Gunn',
				'r/htmx',
				'r/japan',
				'r/LearnJapanese',
				'r/LeverGuns',
				'r/MassImmersionApproach',
				'r/migraine',
				'r/MilitaryGear',
				'r/Norway',
				'r/opensource',
				'r/OutOfTheLoop',
				'r/solotravel',
				'r/teachinginjapan',
				'r/technology',
				'r/weddingplanning',
				'r/WTF',
			],
			System: ['Broken System', 'Bureaucracy', 'Capitalism', 'Law'],
			'Tech Industry': [
				'Coding',
				'Computer Science',
				'Cybersecurity',
				'Indie Hacking',
				'Learn Programming Language',
				'Mixed Reality',
				'No Code',
				'Node.js',
				'Virtual Reality',
				'Web Development',
			],
			Term: ['Compound Word', 'Foreign Term', 'Multi-Word Adjective', 'Slang'],
			Thailand: ['Thai Music'],
			TikTok: ['TikTok Comment'],
			'Traditional Education': ['College', 'Gunn High School'],
			Train: ['Amtrak'],
			Transportation: ['Aviation', 'Bicycle', 'Electric Transportation', 'Public Transit', 'Train'],
			Travel: ['Tourism', 'Travel Restriction'],
			Trivia: ['Phenomenon', 'World Record'],
			Tutorial: ['How to Paint', 'Learn Programming Language', 'Learn to Cook'],
			Tweet: ['Twitter Thread'],
			Twitter: ['Tweet'],
			Typing: ['Computer Keyboard'],
			USA: ['United States of America'],
			'United States of America': [
				'Alabama',
				'American Cultural Export',
				'California',
				'Chinese American Cultural Export',
				'Florida',
				'Illinois',
				'Japanese American',
				'Maryland',
				'Nebraska',
				'New York',
				'South Dakota',
				'USA',
			],
			'Urban Planning': ['Public Transit'],
			'Video Game': ['Browser Video Game', 'Video Game Music'],
			Wartime: ['War Movie'],
			Water: ['Water Purification'],
			Weapon: ['Gun'],
			'Web Development': ['Cascading Style Sheets', 'Fun Website', 'htmx'],
			Wokism: ['Woke'],
			Woodworking: ['Carpentry', 'Woodworker'],
			'Work Culture': ['Hustle Culture'],
			YouTube: ['YouTube Comment', 'YouTube Playlist'],
			htmx: ['r/htmx'],
		},
		loners: ['Idea', 'Mindapp', 'Mystery Solved'],
	},
};

export default env;
